### ISSUE TITLE
Track unique visitors?

### ISSUE THREAD

**Issue by ENTPRESTIGIOUS** [ESKYoung/shields-io-visitor-counter#11]
Is it possible?

**Comment by ESKYoung** [comment]
Sorry @ENTPRESTIGIOUS, it's pretty simplistic, and does not track any users. It works by counting the number of requests to load the image, so can't track or distinguish users!

**Comment by ENTPRESTIGIOUS** [comment]
> Sorry @ENTPRESTIGIOUS, it's pretty simplistic, and does not track any users. It works by counting the number of requests to load the image, so can't track or distinguish users!

So there's no way it can be implemented. Bummer!

**Comment by ESKYoung** [comment]
Nope, sorry! Deliberate choice as it makes things a lot easier from a database storage and privacy perspective too!

**Comment by ENTPRESTIGIOUS** [comment]
> Nope, sorry! Deliberate choice as it makes things a lot easier from a database storage and privacy perspective too!

Thanks for replying though!

**Comment by ESKYoung** [comment]
No problem @ENTPRESTIGIOUS — for a bit of clarity, the project uses [CountAPI](https://countapi.xyz/) to record the counts, so I don't have control over how it counts!

Theoretically, [you could swap out CountAPI for another counting service (or your own) that tracks IPs](https://github.com/ESKYoung/shields-io-visitor-counter/blob/aef0c2049a4c64741006b01a3d4dbc75df712975/main.py#L80). Fair warning, you might (probably will) need a privacy policy as you'll be tracking users!

I'll edit `CONTRIBUTING.md` to make it a bit clearer about what environment variables need to be set, as the `URL_COUNTAPI` variable should be set to call the `hit` CountAPI endpoint.
